apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cron
  labels:
    app: scheduled-demo
spec:
  # Run every minute
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.35
            command:
            - sh
            - -c
            - |
              echo "Hello from CronJob at $(date)"
              echo "Current time: $(date '+%Y-%m-%d %H:%M:%S')"
              echo "Pod name: $HOSTNAME"
            resources:
              requests:
                memory: "16Mi"
                cpu: "25m"
          restartPolicy: OnFailure
