apiVersion: v1
kind: Pod
metadata:
  name: adapter-pod
spec:
  volumes:
    - name: nginx-logs
      emptyDir: {}
    - name: apache-logs
      emptyDir: {}
  containers:
    - name: app-nginx
      image: nginx:1.24-alpine
      volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
    - name: app-apache
      image: httpd:2.4-alpine
      volumeMounts:
        - name: apache-logs
          mountPath: /usr/local/apache2/logs
    - name: log-adapter
      image: busybox:1.35
      command: ["/bin/sh", "-c"]
      args:
        - |
          while true; do
            if [ -f /nginx-logs/access.log ]; then
              tail -n 0 -f /nginx-logs/access.log | while read line; do
                echo "{\"source\":\"nginx\",\"timestamp\":\"$(date -Iseconds)\",\"message\":\"$line\"}"
              done &
            fi
            if [ -f /apache-logs/access_log ]; then
              tail -n 0 -f /apache-logs/access_log | while read line; do
                echo "{\"source\":\"apache\",\"timestamp\":\"$(date -Iseconds)\",\"message\":\"$line\"}"
              done &
            fi
            sleep 60
          done
      volumeMounts:
        - name: nginx-logs
          mountPath: /nginx-logs
        - name: apache-logs
          mountPath: /apache-logs
