apiVersion: v1
kind: ConfigMap
metadata:
  name: log-processor-config
data:
  processor.py: |
    import re
    import json
    import time
    import sys
    from datetime import datetime
    
    def parse_nginx_log(line):
        """Parse nginx access log line into structured data"""
        # Nginx log format: IP - - [timestamp] "method path protocol" status size "referer" "user-agent"
        pattern = r'(\S+) - - \[([^\]]+)\] "(\S+) (\S+) (\S+)" (\d+) (\d+) "([^"]*)" "([^"]*)"'
        match = re.match(pattern, line.strip())
        
        if match:
            return {
                "timestamp": datetime.now().isoformat(),
                "client_ip": match.group(1),
                "request_time": match.group(2),
                "method": match.group(3),
                "path": match.group(4),
                "protocol": match.group(5),
                "status_code": int(match.group(6)),
                "response_size": int(match.group(7)),
                "referer": match.group(8),
                "user_agent": match.group(9),
                "severity": "INFO" if int(match.group(6)) < 400 else "WARN" if int(match.group(6)) < 500 else "ERROR"
            }
        return None
    
    def process_logs():
        """Main log processing function"""
        print("Advanced log processor starting...")
        
        log_file = "/shared-logs/access.log"
        
        # Wait for log file
        while True:
            try:
                with open(log_file, 'r') as f:
                    break
            except FileNotFoundError:
                print("Waiting for log file...")
                time.sleep(2)
        
        print(f"Monitoring {log_file}")
        
        # Follow the log file
        with open(log_file, 'r') as f:
            # Go to end of file
            f.seek(0, 2)
            
            while True:
                line = f.readline()
                if line:
                    parsed = parse_nginx_log(line)
                    if parsed:
                        # Output structured JSON log
                        print(json.dumps(parsed))
                        
                        # Alert on errors
                        if parsed['status_code'] >= 500:
                            alert = {
                                "alert": "HTTP_5XX_ERROR",
                                "timestamp": datetime.now().isoformat(),
                                "details": parsed
                            }
                            print(f"ALERT: {json.dumps(alert)}", file=sys.stderr)
                else:
                    time.sleep(0.1)
    
    if __name__ == "__main__":
        process_logs()
---
apiVersion: v1
kind: Pod
metadata:
  name: advanced-sidecar-demo
  labels:
    app: advanced-sidecar
spec:
  containers:
  # Main application
  - name: web-app
    image: nginx:1.24-alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx
    - name: nginx-config
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: nginx.conf
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
  
  # Advanced log processing sidecar
  - name: log-processor
    image: python:3.11-alpine
    command:
    - python
    - /scripts/processor.py
    volumeMounts:
    - name: shared-logs
      mountPath: /shared-logs
    - name: log-processor-config
      mountPath: /scripts
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
  
  # Log forwarder sidecar
  - name: log-forwarder
    image: busybox:1.35
    command:
    - sh
    - -c
    - |
      echo "Log forwarder starting..."
      
      # Simulate forwarding structured logs to external system
      while true; do
        if [ -f /shared-logs/access.log ]; then
          # Count log entries
          CURRENT_LINES=$(wc -l < /shared-logs/access.log 2>/dev/null || echo 0)
          LAST_LINES=${LAST_LINES:-0}
          
          if [ $CURRENT_LINES -gt $LAST_LINES ]; then
            NEW_ENTRIES=$((CURRENT_LINES - LAST_LINES))
            echo "Forwarding $NEW_ENTRIES new log entries to external system"
            echo "Total entries processed: $CURRENT_LINES"
            LAST_LINES=$CURRENT_LINES
          fi
        fi
        sleep 5
      done
    volumeMounts:
    - name: shared-logs
      mountPath: /shared-logs
    resources:
      requests:
        memory: "16Mi"
        cpu: "25m"
  
  volumes:
  - name: shared-logs
    emptyDir: {}
  - name: log-processor-config
    configMap:
      name: log-processor-config
      defaultMode: 0755
  - name: nginx-config
    configMap:
      name: nginx-custom-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-custom-config
data:
  nginx.conf: |
    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        
        location /api {
            return 200 '{"status":"ok","timestamp":"${time_iso8601}"}';
            add_header Content-Type application/json;
        }
        
        location /error {
            return 500 '{"error":"Internal Server Error"}';
            add_header Content-Type application/json;
        }
        
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
    }
