apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  labels:
    app: blue-green
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue-green
      version: green
  template:
    metadata:
      labels:
        app: blue-green
        version: green
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
