apiVersion: v1
kind: Pod
metadata:
  name: init-failure-demo
spec:
  initContainers:
  # This init container will succeed
  - name: init-success
    image: busybox:1.35
    command:
    - sh
    - -c
    - |
      echo "Successful init container"
      echo "setup_complete=true" > /shared/status.txt
      exit 0
    volumeMounts:
    - name: shared
      mountPath: /shared
  
  # This init container will fail
  - name: init-failure
    image: busybox:1.35
    command:
    - sh
    - -c
    - |
      echo "This init container will fail after checking previous step"
      
      if [ -f /shared/status.txt ]; then
        echo "Previous init container completed:"
        cat /shared/status.txt
      fi
      
      echo "Simulating failure..."
      exit 1
    volumeMounts:
    - name: shared
      mountPath: /shared
  
  # This init container will never run due to previous failure
  - name: init-never-runs
    image: busybox:1.35
    command:
    - sh
    - -c
    - |
      echo "This should never be printed"
      exit 0
  
  containers:
  # Main container will never start
  - name: main-app
    image: busybox:1.35
    command:
    - sh
    - -c
    - |
      echo "Main application starting..."
      while true; do
        echo "App running..."
        sleep 30
      done
  
  volumes:
  - name: shared
    emptyDir: {}
  
  restartPolicy: Never