apiVersion: v2
name: my-web-app
description: A custom Helm chart for a web application
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/mycompany/my-web-app
sources:
  - https://github.com/mycompany/my-web-app
maintainers:
  - name: Eduardo Flores
    email: edu.flores@company.com
keywords:
  - web
  - application
  - nginx
annotations:
  category: Infrastructure
