apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: project-earthflower
  name: project-earthflower
  namespace: earth
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: project-earthflower
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: project-earthflower
    spec:
      containers:
      - image: httpd:2.4.41-alpine
        imagePullPolicy: IfNotPresent
        name: httpd
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: earthflower-volume
          mountPath: /tmp/project-data
      volumes:
      - name: earthflower-volume
        persistentVolumeClaim:
          claimName: earth-project-earthflower-pvc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
