# ConfigMap created separately with real scripts
---
apiVersion: v1
kind: Service
metadata:
  name: logging-demo-app
spec:
  selector:
    app: logging-demo
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-demo
  labels:
    app: logging-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging-demo
  template:
    metadata:
      labels:
        app: logging-demo
    spec:
      containers:
      # Main application containers
      - name: web-api
        image: python:3.11-alpine
        command:
        - sh
        - -c
        - |
          pip install flask requests && python /app/web-api.py
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: app-scripts
          mountPath: /app
        - name: shared-logs
          mountPath: /logs
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
      
      - name: database-client
        image: python:3.11-alpine
        command:
        - sh
        - -c
        - |
          pip install pandas && python /app/database-client.py
        volumeMounts:
        - name: app-scripts
          mountPath: /app
        - name: shared-logs
          mountPath: /logs
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
      
      - name: background-worker
        image: python:3.11-alpine
        command:
        - sh
        - -c
        - |
          python /app/background-worker.py
        volumeMounts:
        - name: app-scripts
          mountPath: /app
        - name: shared-logs
          mountPath: /logs
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
      
      # Logging sidecar containers
      - name: log-collector
        image: python:3.11-alpine
        command:
        - sh
        - -c
        - |
          python /app/log-collector.py
        volumeMounts:
        - name: app-scripts
          mountPath: /app
        - name: shared-logs
          mountPath: /logs
        - name: collected-logs
          mountPath: /collected-logs
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      
      - name: log-processor
        image: python:3.11-alpine
        command:
        - sh
        - -c
        - |
          pip install pandas && python /app/log-processor.py
        volumeMounts:
        - name: app-scripts
          mountPath: /app
        - name: collected-logs
          mountPath: /collected-logs
        - name: processed-logs
          mountPath: /processed-logs
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
      
      - name: log-forwarder
        image: busybox:1.35
        command:
        - sh
        - -c
        - |
          # Simple log forwarder that outputs processed logs
          while true; do
            echo "=== Log Forward Report $(date) ==="
            if [ -d /processed-logs ]; then
              find /processed-logs -name "*.log" -exec wc -l {} \; 2>/dev/null || true
              echo "Latest processed logs:"
              find /processed-logs -name "processed_*" -type f -exec tail -5 {} \; 2>/dev/null || true
            fi
            echo "=== End Report ==="
            sleep 60
          done
        volumeMounts:
        - name: processed-logs
          mountPath: /processed-logs
        resources:
          requests:
            memory: "64Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      
      volumes:
      - name: app-scripts
        configMap:
          name: app-scripts
          defaultMode: 0755
      - name: shared-logs
        emptyDir: {}
      - name: collected-logs
        emptyDir: {}
      - name: processed-logs
        emptyDir: {}
---
# Optional: Create a monitoring pod to observe logs
apiVersion: v1
kind: Pod
metadata:
  name: log-monitor
  labels:
    app: log-monitor
spec:
  containers:
  - name: monitor
    image: busybox:1.35
    command:
    - sh
    - -c
    - |
      echo "Log monitoring started..."
      while true; do
        echo "=== Log Monitor Report $(date) ==="
        echo "Checking application logs..."
        kubectl logs deployment/logging-demo -c web-api --tail=5 2>/dev/null || echo "Could not fetch web-api logs"
        kubectl logs deployment/logging-demo -c log-collector --tail=5 2>/dev/null || echo "Could not fetch log-collector logs"
        kubectl logs deployment/logging-demo -c log-processor --tail=5 2>/dev/null || echo "Could not fetch log-processor logs"
        echo "=== End Monitor Report ==="
        sleep 120
      done
    resources:
      requests:
        memory: "64Mi"
        cpu: "25m"
      limits:
        memory: "128Mi"
        cpu: "100m"
  restartPolicy: Always