FROM python:3.11-alpine

# Create non-root user
RUN adduser -D appuser

# No secrets in the image
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY --chown=appuser:appuser app-secrets.py .

USER appuser

# Secrets will be provided at runtime
CMD ["python", "app-secrets.py"]
