# Usamos un DaemonSet para el agente de monitoreo porque debe ejecutarse en cada nodo del clúster.

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-monitor
spec:
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
      - name: monitor
        image: prom/node-exporter
        ports:
        - containerPort: 9100
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
