apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-calculator
  labels:
    type: parallel-demo
spec:
  # Need 6 total completions
  completions: 6
  # Run 3 pods in parallel
  parallelism: 3
  backoffLimit: 2
  template:
    metadata:
      labels:
        type: parallel-demo
    spec:
      containers:
      - name: calculator
        image: python:3.11-alpine
        command:
        - python
        - -c
        - |
          import time
          import random
          import os
          import math
          
          pod_name = os.getenv('HOSTNAME', 'unknown')
          completion_index = os.getenv('JOB_COMPLETION_INDEX', '0')
          
          print(f"Pod {pod_name} (completion {completion_index}) starting...")
          
          # Simulate different work based on completion index
          numbers = [10, 15, 20, 25, 30, 35]
          number = numbers[int(completion_index) % len(numbers)]
          
          print(f"Calculating factorial of {number}...")
          
          # Simulate work time
          work_time = random.uniform(3, 8)
          time.sleep(work_time)
          
          result = math.factorial(number)
          print(f"Pod {pod_name}: factorial({number}) = {result}")
          print(f"Pod {pod_name} completed in {work_time:.2f} seconds")
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      restartPolicy: Never
