apiVersion: v1
kind: Pod
metadata:
  name: sidecar-logging
  labels:
    app: web-with-sidecar
spec:
  containers:
  - name: web-app
    image: nginx:1.24-alpine
    volumeMounts:
    - name: log-volume
      mountPath: /var/log/nginx
  - name: log-processor
    image: busybox:1.35
    command: ["sh", "-c", "while true; do if [ -f /shared-logs/access.log ]; then echo '[PROCESSED]' $(tail -n 1 /shared-logs/access.log); fi; sleep 10; done"]
    volumeMounts:
    - name: log-volume
      mountPath: /shared-logs
  volumes:
  - name: log-volume
    emptyDir: {}