apiVersion: v1
kind: Pod
metadata:
  name: advanced-liveness
  labels:
    app: advanced-app
spec:
  containers:
  - name: app
    image: alpine:3.18
    command:
    - sh
    - -c
    - |
      # Install curl for HTTP checks
      apk add --no-cache curl
      
      # Start a simple HTTP server in background
      cat << 'SERVER' > server.py
      import http.server
      import socketserver
      import threading
      import time
      import os
      
      class HealthHandler(http.server.BaseHTTPRequestHandler):
          def do_GET(self):
              if self.path == '/health':
                  # Check multiple health indicators
                  cpu_ok = os.path.exists('/tmp/cpu_ok')
                  memory_ok = os.path.exists('/tmp/memory_ok')
                  disk_ok = os.path.exists('/tmp/disk_ok')
                  
                  if cpu_ok and memory_ok and disk_ok:
                      self.send_response(200)
                      self.send_header('Content-type', 'application/json')
                      self.end_headers()
                      self.wfile.write(b'{"status":"healthy","checks":{"cpu":true,"memory":true,"disk":true}}')
                  else:
                      self.send_response(500)
                      self.send_header('Content-type', 'application/json')
                      self.end_headers()
                      self.wfile.write(b'{"status":"unhealthy","checks":{"cpu":' + str(cpu_ok).lower().encode() + b',"memory":' + str(memory_ok).lower().encode() + b',"disk":' + str(disk_ok).lower().encode() + b'}}')
              else:
                  self.send_response(404)
                  self.end_headers()
      
      # Create initial health indicators
      os.system('touch /tmp/cpu_ok /tmp/memory_ok /tmp/disk_ok')
      
      # Start server
      httpd = socketserver.TCPServer(("", 8080), HealthHandler)
      httpd.serve_forever()
      SERVER
      
      python3 server.py
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
        httpHeaders:
        - name: User-Agent
          value: Kubernetes-Liveness-Probe
      initialDelaySeconds: 20
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
      requests:
        memory: "64Mi"
        cpu: "50m"
